name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Refresh tags and categories for the Solodit
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://solodit.xyz/api/general/refresh_tag_category/'
        method: 'POST'
        email: ${{ secrets.SOLODIT_USER }}
        password: ${{ secrets.SOLODIT_PASSWORD }}
        # customHeaders: '{"Content-Type": "application/json"}'
        # data: '{"key_1": "value_1", "key_2": "value_2"}'